### ISSUE TITLE
mysql extension deprecated

### ISSUE THREAD

**Issue by artisaninweb** [Drarok/ladder#1]
Getting a error that the mysql extension is deprecated.
Can you please replace it with mysqli or pdo?

Thanks.

**Comment by Drarok** [comment]
Apologies, I've only just seen this issue! :disappointed_relieved: 

There's no plans to replace mysql in this version, though I have a from-scratch rewrite which uses PDO, which I planned to release as v2 (or possibly v3, since there was an ill-thought-out v2 in the works for a while).

I presume given the age of this ticket, it's no longer a problem?
